FROM openjdk:17-jdk-slim-buster
COPY target/WeddingVenuePlanning-0.0.1-SNAPSHOT.jar WeddingVenuePlanning-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","WeddingVenuePlanning-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080:8080